---
title: "Milestone 2"
author: "Arjun Akwei"
date: "9/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The first project that I looked to analyze was Lindsey Greenhill’s website tracking human trafficking. I found it fascinating how she connected it to an issue from another class, Professor Orlando Patterson's Gened1115: Human Trafficking, Slavery and Abolition in the Modern World, as this allowed for her to have a strong contextual foundation on the subject matter. Given how compelling of a project this allowed her to create, I think it is worth noting the importance of a comprehensive understanding of the topic before the data analysis part begins. This allowed her, and will hopefully allow me, to determine what exactly I want to be studying and displaying. It was also helpful how she really walked viewers through where the data came from and then every step of breaking down the issue. The recognition that this sample may not be perfectly representative of the population but is simply the best that could be found is also a good display of temperance. The sheer number of displays is also an incredible display of commitment: the fact that almost every aspect of the data can be viewed in a narrow, easily digested manner is incredibly helpful, though undoubtedly a lot of work. I also found it impressive how she connected her data to variables I would never have thought to look at. All in all, the project was incredibly impressive. I think one area for improvement might be in the general aesthetics of the page. While it is clear that a lot of time was taken to make the individual graphs and charts look nice, the page itself could be cleaned up a little bit (very minor).Finally, the question is raised of why certain countries had far lower numbers reported, and how this can be reflected in the data.

The second project I looked at was Yao Yu's project on gun violence. Yao's project was really well done because it allowed us to really dive into the issue with a solution-oriented focus. I thought that establishing this framework early on was a helpful guide in interpreting the data. I thought the variables he chose to include were particularly thoughtful, namely in the imprisonment and and violent crime section. I think an important lesson to take away is that one must be mindful in picking what you choose to display. This leads me to one of the few cons of Yao's presentation. The regression on violent crime and gun control laws for example seemed unnecessary for San Francisco for example, as the line did not really follow a pattern. Here it is important that not everything that can be plotted should be.
